name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  mix_test:
    name: mix test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: 23.1
          elixir-version: 1.11.0
      - name: Install Dependencies
        run: |
          mix local.hex --force
          mix deps.get --only test
      - run: mix test

  check_formatted:
    name: Check formatted
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: 23.1
          elixir-version: 1.11.0
      - run: mix format --check-formatted
